### ISSUE TITLE
v0.7 panick at launch

### ISSUE THREAD

**Issue by Tbaut** [Manta-Network/manta-signer#114]
I installed the `.deb` and also played with the AppImage and the same happens, it panicks right away on Linux mint 20.3 which is ubuntu based.

```
RUST_BACKTRACE=full  ./manta-signer-ubuntu-latest_0.7.0-100_amd64.AppImage
thread 'main' panicked at 'Can't detect any appindicator library', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libappindicator-sys-0.7.2/src/lib.rs:55:15
stack backtrace:
   0:     0x55aa12ccb84d - std::backtrace_rs::backtrace::libunwind::trace::h22893a5306c091b4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55aa12ccb84d - std::backtrace_rs::backtrace::trace_unsynchronized::h29c3bc6f9e91819d
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55aa12ccb84d - std::sys_common::backtrace::_print_fmt::he497d8a0ec903793
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55aa12ccb84d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c2a9d2774d81873
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55aa12cf131c - core::fmt::write::hba4337c43d992f49
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
   5:     0x55aa12cc4241 - std::io::Write::write_fmt::heb73de6e02cfabed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
   6:     0x55aa12ccd675 - std::sys_common::backtrace::_print::h63c8b24acdd8e8ce
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55aa12ccd675 - std::sys_common::backtrace::print::h426700d6240cdcc2
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55aa12ccd675 - std::panicking::default_hook::{{closure}}::hc9a76eed0b18f82b
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
   9:     0x55aa12ccd329 - std::panicking::default_hook::h2e88d02087fae196
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
  10:     0x55aa12ccdbc2 - std::panicking::rust_panic_with_hook::habfdcc2e90f9fd4c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:698:17
  11:     0x55aa12a343bb - std::panicking::begin_panic::{{closure}}::h5bf3a1687ab95f5b
  12:     0x55aa12a34384 - std::sys_common::backtrace::__rust_end_short_backtrace::h7536b37a4688ddeb
  13:     0x55aa12724b9a - std::panicking::begin_panic::hd4adc344912f9ed2
  14:     0x55aa12a3366f - libappindicator_sys::get_appindicator_library_path::h0fd09699709fc91f
  15:     0x55aa12a32898 - core::ops::function::FnOnce::call_once::h13a6df38a6f49432
  16:     0x55aa12a3428a - once_cell::imp::OnceCell<T>::initialize::{{closure}}::h073fa242c065f37a
  17:     0x55aa12ca07a1 - once_cell::imp::initialize_or_wait::h47dff430fe28ddbf
  18:     0x55aa12724ac2 - once_cell::imp::OnceCell<T>::initialize::h5901de5d021e560b
  19:     0x55aa12a33a5a - libappindicator_sys::app_indicator_new_with_path::h23bd0168e0dc3190
  20:     0x55aa12a321e3 - libappindicator::AppIndicator::with_path::h0a751a3c5064e4c3
  21:     0x55aa12a2644a - tao::system_tray::SystemTrayBuilder::new::h744b9464252cde66
  22:     0x55aa127f6b23 - <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::system_tray::h8fa08bffdb2b8da0
  23:     0x55aa1291aefd - tauri::app::Builder<R>::build::hdfb96dbe78570abf
  24:     0x55aa128050f5 - manta_signer_ui::main::h766e2e16abf00088
  25:     0x55aa128241f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha4b2825ee9e928a9
  26:     0x55aa12889739 - std::rt::lang_start::{{closure}}::h66f1f9465828f58d
  27:     0x55aa12cbdfbe - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::had4f69b3aefb47a8
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
  28:     0x55aa12cbdfbe - std::panicking::try::do_call::hf2ad5355fcafe775
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  29:     0x55aa12cbdfbe - std::panicking::try::h0a63ac363423e61e
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  30:     0x55aa12cbdfbe - std::panic::catch_unwind::h18088edcecb8693a
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  31:     0x55aa12cbdfbe - std::rt::lang_start_internal::{{closure}}::ha7dad166dc711761
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
  32:     0x55aa12cbdfbe - std::panicking::try::do_call::hda0c61bf3a57d6e6
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  33:     0x55aa12cbdfbe - std::panicking::try::hbc940e68560040a9
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  34:     0x55aa12cbdfbe - std::panic::catch_unwind::haed0df2aeb3fa368
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  35:     0x55aa12cbdfbe - std::rt::lang_start_internal::h9c06694362b5b80c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
  36:     0x55aa12806e12 - main
  37:     0x7fc2ca428083 - __libc_start_main
  38:     0x55aa12734b6e - _start
  39:                0x0 - <unknown>

```

**Comment by Tbaut** [comment]
The installer didn't show any dep I'd need to install, I installed it manually now
```
libayatana-appindicator3-1 is already the newest version (0.5.4-2)
```
but it still panicks with the same error.

The installer did't have any error or showed anything worrying
![image](https://user-images.githubusercontent.com/33178835/174170856-10198115-8ad8-468a-88e0-5f87b3a89c80.png)

**Comment by Tbaut** [comment]
The same happens with v7.1

**Comment by Tbaut** [comment]
Probably not a surprise but still the case on 0.7.2
